import { PDFTool, ToolConfig } from '@/types/tools';
import { PDFToolType } from '@/types/pdf';

export const PDF_TOOLS: PDFTool[] = [
  {
    id: PDFToolType.MERGE,
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into one document',
    href: '/merge-pdf',
    icon: 'DocumentDuplicateIcon',
    color: 'bg-blue-500',
    category: 'edit',
    features: [
      'Combine unlimited PDF files',
      'Drag and drop to reorder',
      'Preview before merging',
      'Maintain original quality',
    ],
  },
  {
    id: PDFToolType.SPLIT,
    name: 'Split PDF',
    description: 'Extract pages or split PDF into multiple files',
    href: '/split-pdf',
    icon: 'ScissorsIcon',
    color: 'bg-green-500',
    category: 'edit',
    features: [
      'Split by page ranges',
      'Extract specific pages',
      'Bulk page extraction',
      'Preview pages before splitting',
    ],
  },
  {
    id: PDFToolType.COMPRESS,
    name: 'Compress PDF',
    description: 'Reduce PDF file size without losing quality',
    href: '/compress-pdf',
    icon: 'ArrowsPointingInIcon',
    color: 'bg-purple-500',
    category: 'optimize',
    features: [
      'Smart compression algorithm',
      'Multiple quality levels',
      'Preserve text quality',
      'Optimize images automatically',
    ],
  },
  {
    id: PDFToolType.PDF_TO_WORD,
    name: 'PDF to Word',
    description: 'Convert PDF documents to editable Word files',
    href: '/pdf-to-word',
    icon: 'DocumentTextIcon',
    color: 'bg-orange-500',
    category: 'convert',
    features: [
      'Maintain formatting',
      'Editable text output',
      'Preserve images and tables',
      'Fast conversion',
    ],
    limitations: [
      'Complex layouts may need adjustment',
      'Scanned PDFs require OCR',
    ],
  },
  {
    id: PDFToolType.WORD_TO_PDF,
    name: 'Word to PDF',
    description: 'Convert Word documents to PDF format',
    href: '/word-to-pdf',
    icon: 'DocumentTextIcon',
    color: 'bg-red-500',
    category: 'convert',
    features: [
      'Perfect formatting preservation',
      'Supports .doc and .docx',
      'Maintains hyperlinks',
      'Professional output',
    ],
  },
  {
    id: PDFToolType.PDF_TO_JPG,
    name: 'PDF to JPG',
    description: 'Convert PDF pages to high-quality images',
    href: '/pdf-to-jpg',
    icon: 'PhotoIcon',
    color: 'bg-pink-500',
    category: 'convert',
    features: [
      'High-resolution output',
      'Convert all or specific pages',
      'Multiple image formats',
      'Batch processing',
    ],
  },
  {
    id: PDFToolType.JPG_TO_PDF,
    name: 'JPG to PDF',
    description: 'Convert images to PDF documents',
    href: '/jpg-to-pdf',
    icon: 'PhotoIcon',
    color: 'bg-indigo-500',
    category: 'convert',
    features: [
      'Multiple images to one PDF',
      'Automatic page sizing',
      'Preserve image quality',
      'Custom page layouts',
    ],
  },
  {
    id: PDFToolType.ROTATE,
    name: 'Rotate PDF',
    description: 'Rotate PDF pages to the correct orientation',
    href: '/rotate-pdf',
    icon: 'ArrowPathIcon',
    color: 'bg-teal-500',
    category: 'edit',
    features: [
      'Rotate individual pages',
      'Bulk rotation options',
      '90°, 180°, 270° rotation',
      'Preview before applying',
    ],
  },
  {
    id: PDFToolType.WATERMARK,
    name: 'Add Watermark',
    description: 'Add text or image watermarks to PDF files',
    href: '/add-watermark',
    icon: 'PaintBrushIcon',
    color: 'bg-yellow-500',
    category: 'edit',
    features: [
      'Text and image watermarks',
      'Customizable position',
      'Adjustable opacity',
      'Batch watermarking',
    ],
  },
];

export const TOOL_CONFIGS: Record<PDFToolType, ToolConfig> = {
  [PDFToolType.MERGE]: {
    maxFileSize: 10 * 1024 * 1024,
    maxFiles: 10,
    supportedInputTypes: ['application/pdf'],
    supportedOutputTypes: ['application/pdf'],
  },
  [PDFToolType.SPLIT]: {
    maxFileSize: 10 * 1024 * 1024,
    maxFiles: 1,
    supportedInputTypes: ['application/pdf'],
    supportedOutputTypes: ['application/pdf'],
    processingOptions: [
      {
        key: 'splitType',
        label: 'Split Type',
        type: 'select',
        options: [
          { value: 'pages', label: 'By Page Range' },
          { value: 'size', label: 'By File Size' },
          { value: 'extract', label: 'Extract Pages' },
        ],
        default: 'pages',
      },
    ],
  },
  [PDFToolType.COMPRESS]: {
    maxFileSize: 10 * 1024 * 1024,
    maxFiles: 1,
    supportedInputTypes: ['application/pdf'],
    supportedOutputTypes: ['application/pdf'],
    processingOptions: [
      {
        key: 'quality',
        label: 'Compression Level',
        type: 'select',
        options: [
          { value: 'low', label: 'High Compression (Lower Quality)' },
          { value: 'medium', label: 'Balanced' },
          { value: 'high', label: 'Low Compression (Higher Quality)' },
        ],
        default: 'medium',
      },
    ],
  },
  [PDFToolType.PDF_TO_WORD]: {
    maxFileSize: 10 * 1024 * 1024,
    maxFiles: 1,
    supportedInputTypes: ['application/pdf'],
    supportedOutputTypes: ['application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
  },
  [PDFToolType.WORD_TO_PDF]: {
    maxFileSize: 10 * 1024 * 1024,
    maxFiles: 1,
    supportedInputTypes: [
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    ],
    supportedOutputTypes: ['application/pdf'],
  },
  [PDFToolType.PDF_TO_JPG]: {
    maxFileSize: 10 * 1024 * 1024,
    maxFiles: 1,
    supportedInputTypes: ['application/pdf'],
    supportedOutputTypes: ['image/jpeg', 'image/png'],
    processingOptions: [
      {
        key: 'format',
        label: 'Output Format',
        type: 'select',
        options: [
          { value: 'jpeg', label: 'JPEG' },
          { value: 'png', label: 'PNG' },
        ],
        default: 'jpeg',
      },
      {
        key: 'quality',
        label: 'Image Quality',
        type: 'range',
        min: 1,
        max: 100,
        step: 1,
        default: 85,
      },
    ],
  },
  [PDFToolType.JPG_TO_PDF]: {
    maxFileSize: 10 * 1024 * 1024,
    maxFiles: 10,
    supportedInputTypes: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'],
    supportedOutputTypes: ['application/pdf'],
  },
  [PDFToolType.ROTATE]: {
    maxFileSize: 10 * 1024 * 1024,
    maxFiles: 1,
    supportedInputTypes: ['application/pdf'],
    supportedOutputTypes: ['application/pdf'],
    processingOptions: [
      {
        key: 'rotation',
        label: 'Rotation Angle',
        type: 'select',
        options: [
          { value: 90, label: '90° Clockwise' },
          { value: 180, label: '180°' },
          { value: 270, label: '270° Clockwise (90° Counter-clockwise)' },
        ],
        default: 90,
      },
    ],
  },
  [PDFToolType.WATERMARK]: {
    maxFileSize: 10 * 1024 * 1024,
    maxFiles: 1,
    supportedInputTypes: ['application/pdf'],
    supportedOutputTypes: ['application/pdf'],
    processingOptions: [
      {
        key: 'text',
        label: 'Watermark Text',
        type: 'text',
        default: 'CONFIDENTIAL',
      },
      {
        key: 'position',
        label: 'Position',
        type: 'select',
        options: [
          { value: 'center', label: 'Center' },
          { value: 'corner', label: 'Corner' },
        ],
        default: 'center',
      },
      {
        key: 'opacity',
        label: 'Opacity',
        type: 'range',
        min: 0.1,
        max: 1,
        step: 0.1,
        default: 0.5,
      },
    ],
  },
};